deeplob:
  batch_size: 128
  learning_rate: 0.01
  epsilon: 1
  epoch: 100
  num_workers: 4

deeplob-lighten:
  batch_size: 128
  learning_rate: 0.0001
  epsilon: 1e-08
  epoch: 30
  num_workers: 4

lobster:
  batch_size: 128
  learning_rate: 0.0001
  epsilon: 1e-08
  epoch: 30
  num_workers: 4

lobster-lighten:
  batch_size: 128
  learning_rate: 0.0001
  epsilon: 1e-08
  epoch: 30
  num_workers: 4

translob:
  batch_size: 128
  learning_rate: 0.01
  epsilon: 1
  epoch: 300
  num_workers: 4
